---
dist: xenial
sudo: required
language: python

services:
  - docker

before_script:
  - cd ../
  - mv ansible-role-supervisor daixijun.supervisor
  - cd daixijun.supervisor

install:
  - pip install ansible molecule docker

script:
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
