---
- name: Ensure python-pip installed
  yum:
    name: python-pip
    state: present

- name: Ensure supervisor installed
  pip:
    name: supervisor
    state: present

- name: Ensure configuration and log paths are present
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/supervisord.d
    - /etc/eventlistener
    - /var/log/supervisord

- name: Ensure supervisor configuration is present
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf
  notify:
    - supervisord restarted

- name: Ensure supervisor program configs are present
  template:
    src: supervisor.program.ini.j2
    dest: /etc/supervisord.d/{{ item.programname }}.ini
  loop: "{{ supervisor_programs }}"
  when:
    - supervisor_programs|length > 0
    - item.state|default('present') != 'absent'
  notify:
    - supervisord update

- name: Ensure supervisor group configs are present
  template:
    src: supervisor.group.ini.j2
    dest: /etc/supervisord.d/group_{{ item.groupname }}.ini
  loop: "{{ supervisor_groups }}"
  when:
    - supervisor_groups is defined and supervisor_groups|length > 0
    - item.state|default('present') != 'absent'
  notify:
    - supervisord update

- name: Ensure crashdingtalk script are absent
  file:
    path: /usr/local/bin/crashdingtalk
    state: absent

- name: Ensure crashdingtalk configuration are absent
  file:
    path: /etc/supervisord.d/{{ item.programname }}.ini
    state: absent
  loop: "{{ supervisor_monitors }}"
  when:
    - supervisor_monitors is defined
    - supervisor_monitors|length > 0
  notify:
    - supervisord update

- name: Ensure program {{ item.programname }} is absent
  file:
    path: /etc/supervisord.d/{{ item.programname }}.ini
    state: absent
  loop: "{{ supervisor_programs }}"
  when:
    - supervisor_programs|length > 0
    - item.state|default('present') == 'absent'
  notify:
    - supervisord update

- name: Ensure group is absent
  file:
    path: /etc/supervisord.d/group_{{ item.groupname }}.ini
    state: absent
  loop: "{{ supervisor_groups }}"
  when:
    - supervisor_groups|length > 0
    - item.state|default('present') == 'absent'
  notify:
    - supervisord update

- name: Upload eventlistener
  copy:
    src: eventlistener
    dest: /usr/local/bin/eventlistener
    owner: root
    group: root
    mode: "0755"
  notify:
    - restart eventlistener

- name: Generator eventlistener configuration file
  copy:
    content: "{{ supervisor_eventlistener | to_nice_yaml(indent=2) }}"
    dest: /etc/eventlistener/config.yaml
    owner: root
    group: root
    mode: "0644"
  when:
    - supervisor_eventlistener|length > 0
  notify:
    - restart eventlistener

- name: Generator eventlistener monitor configuration file
  copy:
    src: eventlistener.ini
    dest: /etc/supervisord.d/eventlistener.ini
    owner: root
    group: root
    mode: "0644"
  when:
    - supervisor_eventlistener|length > 0
  notify:
    - supervisord update
    - restart eventlistener

- name: Startup for systemd
  template:
    src: supervisord.service.j2
    dest: /etc/systemd/system/supervisord.service
  when: ansible_service_mgr == 'systemd'

- name: Ensure supervisor is started
  systemd:
    name: supervisord
    state: started
    enabled: yes
    daemon_reload: true
  when: ansible_service_mgr == 'systemd'
