---
- name: supervisord update
  command: supervisorctl update
  args:
    warn: no

- name: supervisord restarted
  systemd:
    name: supervisord
    state: restarted
    enabled: yes

- name: restart eventlistener
  supervisorctl:
    name: eventlistener
    state: restarted
  when:
    - supervisor_eventlistener|length > 0
