---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Gather service facts
      service_facts:
      no_log: true

    - name: Assert that supervisord service is running
      assert:
        that:
          - ansible_facts.services['supervisord.service'].state == "running"
          - ansible_facts.services['supervisord.service'].status == "enabled"

    - name: Waitting supervisord http server started
      wait_for:
        host: 0.0.0.0
        port: 9001
        state: started
        timeout: 10

    - name: Get process cat state
      command: supervisorctl status cat
      register: __process_cat_status
      tags:
        - skip_ansible_lint

    - name: Asset that process cat is running
      assert:
        that:
          - "'RUNNING' in __process_cat_status.stdout"
